steps:
  # Build project
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install', '--quiet', '-DpomFile=gcp_pom.xml']

  # Deploy app
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version=prod']